uarttest

diff --git a/.github/workflows/Test.yml b/.github/workflows/Test.yml
--- a/.github/workflows/Test.yml
+++ b/.github/workflows/Test.yml
@@ -79,9 +79,15 @@ jobs:
           cd firmware-tests
           make
 
-      # 11. Ejecutar tests con QEMU
-      - name: Run QEMU tests
+       - name: Run QEMU test: uartTest
         run: |
-          cd firmware-tests
-          chmod +x ./runQEMU
-          ./runQEMU
+          chmod +x firmware-tests/runQEMU
+          echo "🧪 Running UART loopback test..."
+          ./firmware-tests/runQEMU uartTest | tee uart.log
+
+      - name: Check loopback test result
+        run: |
+          if ! grep -q "UART loopback test PASSED" uart.log; then
+            echo "❌ UART loopback test failed: expected output not found"
+            exit 1
+          fi
